/** Rusça → Türkçe ürün/kozmetik terim sözlüğü (API gerektirmez) */
const PHRASES = [
  ['ниацинамид', 'niasinamid'],
  ['увлажняющий', 'nemlendirici'],
  ['увлажняет', 'nemlendirir'],
  ['увлажнение', 'nemlendirme'],
  ['крем для лица', 'yüz kremi'],
  ['крем', 'krem'],
  ['женский', 'kadın'],
  ['мужской', 'erkek'],
  ['мужские', 'erkek'],
  ['детский', 'çocuk'],
  ['для душа', 'duş jeli'],
  ['гель для душа', 'duş jeli'],
  ['шампунь', 'şampuan'],
  ['зубная паста', 'diş macunu'],
  ['зубная щётка', 'diş fırçası'],
  ['зубная щетка', 'diş fırçası'],
  ['мыло', 'sabun'],
  ['средство для стирки', 'çamaşır deterjanı'],
  ['стиральный порошок', 'çamaşır deterjanı'],
  ['антибактериальный', 'antibakteriyel'],
  ['освежитель воздуха', 'hava temizleyici'],
  ['ароматический', 'aromatik'],
  ['лосьон', 'losyon'],
  ['маска для волос', 'saç maskesi'],
  ['маска', 'maske'],
  ['помада для губ', 'dudak ruju'],
  ['помада', 'ruj'],
  ['духи', 'parfüm'],
  ['туалетная бумага', 'tuvalet kağıdı'],
  ['салфетки', 'mendil'],
  ['носки', 'çorap'],
  ['трусы', 'külot'],
  ['тапочки', 'terlik'],
  ['полотенце', 'havlu'],
  ['зонт', 'şemsiye'],
  ['очки', 'gözlük'],
  ['солнцезащитные очки', 'güneş gözlüğü'],
  ['расческа', 'tarak'],
  ['ватные палочки', 'kulak çubuğu'],
  ['прокладка', 'hijyenik ped'],
  ['гигиеническая прокладка', 'hijyenik ped'],
  ['капсулы', 'kapsül'],
  ['витамин', 'vitamin'],
  ['жевательные таблетки', 'çiğnenebilir tablet'],
  ['гладкость', 'pürüzsüzlük'],
  ['кожи', 'cilt'],
  ['кожу', 'cildi'],
  ['кожа', 'cilt'],
  ['волос', 'saç'],
  ['волосы', 'saç'],
  ['эластичность', 'esneklik'],
  ['упругость', 'sıkılık'],
  ['пантенол', 'pantenol'],
  ['коллаген', 'kolajen'],
  ['экстракт', 'özüt'],
  ['пептид', 'peptit'],
  ['натуральный', 'doğal'],
  ['органический', 'organik'],
  ['комфорт', 'konfor'],
  ['лёгкие', 'hafif'],
  ['легкие', 'hafif'],
  ['ежедневный', 'günlük'],
  ['ежедневное', 'günlük'],
  ['помогает', 'yardımcı olur'],
  ['способствует', 'destekler'],
  ['содержит', 'içerir'],
  ['подходит', 'uygun'],
  ['изготовлены', 'üretilmiştir'],
  ['из натурального', 'doğal'],
  ['хлопка', 'pamuk'],
  ['льна', 'keten'],
  ['резиновая подошва', 'kauçuk taban'],
  ['текстиль', 'tekstil'],
  ['упаковка', 'paket'],
  ['коробке', 'kutu'],
  ['кол-во в коробке', 'kutu adedi'],
  ['шт', 'adet'],
  ['пар', 'çift'],
  ['размер', 'beden'],
  ['синие', 'mavi'],
  ['черные', 'siyah'],
  ['серые', 'gri'],
  ['белые', 'beyaz'],
  ['зеленые', 'yeşil'],
  ['летние', 'yazlık'],
  ['домашний', 'ev'],
  ['домашнего', 'ev'],
  ['стирки', 'yıkama'],
  ['чистки', 'temizlik'],
  ['очищающий', 'temizleyici'],
  ['очищающая', 'temizleyici'],
  ['отбеливатель', 'ağartıcı'],
  ['пятен', 'leke'],
  ['машины', 'makine'],
  ['обуви', 'ayakkabı'],
  ['белья', 'çamaşır'],
  ['нижнего белья', 'iç çamaşırı'],
  ['интимной гигиены', 'özel hijyen'],
  ['уход', 'bakım'],
  ['ухода', 'bakım'],
  ['салонный', 'salon'],
  ['профессиональный', 'profesyonel'],
  ['аромат', 'koku'],
  ['цветочный', 'çiçek'],
  ['чай', 'çay'],
  ['зеленый чай', 'yeşil çay'],
  ['алоэ', 'aloe vera'],
  ['ромашка', 'papatya'],
  ['лаванда', 'lavanta'],
  ['вишни', 'kiraz'],
  ['роза', 'gül'],
  ['черника', 'yaban mersini'],
  ['шоколадный вкус', 'çikolata aromalı'],
  ['мягкое', 'yumuşak'],
  ['мягкие', 'yumuşak'],
  ['конфеты', 'şeker'],
  ['постельного белья', 'yatak takımı'],
  ['хлопка', 'pamuk'],
  ['порошок', 'toz'],
  ['без фосфорной кислоты', 'fosforsuz'],
  ['полотенце', 'havlu'],
  ['банное', 'banyo'],
  ['гель для укладки волос', 'saç şekillendirme jeli'],
  ['стик для шеи', 'boyun stick'],
  ['бритва', 'tıraş bıçağı'],
  ['ручная', 'manuel'],
  ['пакет', 'poşet'],
  ['целлофановый', 'selofan'],
  ['майка', 'atlet'],
  ['средний', 'orta'],
  ['большая', 'büyük'],
  ['маленький', 'küçük'],
  ['мини', 'mini'],
  ['набор', 'set'],
  ['эссенций', 'esans'],
  ['утро-вечер', 'sabah-akşam'],
  ['микрогранулами', 'mikro granüller'],
  ['аминокислотная', 'amino asit'],
  ['пенка', 'köpük'],
  ['умывания', 'yüz yıkama'],
  ['скраб', 'scrub'],
  ['контролем жирности', 'yağ kontrolü'],
  ['360-градусные', '360 derece'],
  ['дышащие', 'nefes alabilen'],
  ['бесшовные', 'dikişsiz'],
  ['жаккардовые', 'jakarlı'],
  ['нижнее белье', 'iç çamaşırı'],
  ['чистого хлопка', 'saf pamuk'],
  ['одна упаковка', 'tek paket'],
  ['одиночная упаковка', 'tek paket'],
  ['английская и русская версия', 'İngilizce ve Rusça versiyon'],
  ['англо-русская версия', 'İngilizce-Rusça versiyon'],
  ['международная версия', 'uluslararası versiyon'],
  ['подарочная коробка', 'hediye kutusu'],
  ['подарочный пакет', 'hediye poşeti'],
  ['складная', 'katlanabilir'],
  ['значок с логотипом', 'logo rozeti'],
  ['мусорный бак', 'çöp kutusu'],
  ['средство для мытья полов', 'yer temizleyici'],
  ['кисть для лица', 'yüz fırçası'],
  ['кисть для бровей', 'kaş fırçası'],
  ['двусторонняя', 'çift taraflı'],
  ['двусторонние', 'çift taraflı'],
  ['краска для волос', 'saç boyası'],
  ['темный каштановый', 'koyu kestane'],
  ['уксус', 'sirke'],
  ['органический уксус', 'organik sirke'],
  ['согревающая', 'ısıtıcı'],
  ['компресс', 'kompres'],
  ['на глаза', 'göz'],
  ['с лавандой', 'lavantalı'],
  ['с эфиром', 'esanslı'],
  ['лютеина', 'lutein'],
  ['овсянки', 'yulaf'],
  ['успокаивающий', 'yatıştırıcı'],
  ['мягкое очищающее', 'yumuşak temizleyici'],
  ['ежедневное полотенце', 'günlük temizlik havlusu'],
  ['жемчужным узором', 'inci desenli'],
  ['съемное', 'çıkarılabilir'],
  ['легкой текстурой', 'hafif doku'],
  ['красные ягоды', 'kırmızı meyve'],
  ['оттенок', 'ton'],
  ['ароматические шарики', 'koku topları'],
  ['для одежды', 'kıyafet için'],
  ['фрезия', 'freesia'],
  ['линзы', 'lens'],
  ['песочно-зелено-серые', 'kum yeşili gri'],
  ['яркие черно-фиолетовые', 'parlak siyah mor'],
  ['защита от синего света', 'mavi ışık koruması'],
  ['чтения', 'okuma'],
  ['черепаховом панцире', 'kaplumbağa kabuğu'],
  ['галстук', 'kravat'],
  ['шелковый', 'ipek'],
  ['однотонного цвета', 'düz renk'],
  ['бамбуковой основе', 'bambu bazlı'],
  ['квадратная', 'kare'],
  ['деревянная', 'ahşap'],
  ['массажная', 'masaj'],
  ['эфирными маслами', 'esansiyel yağlar'],
  ['аминокислотами', 'amino asitler'],
  ['ароматный и увлажняющий', 'aromatik ve nemlendirici'],
  ['средство для чистки', 'temizleyici'],
  ['стиральной машины', 'çamaşır makinesi'],
  ['материал для оклейки мебели', 'mobilya kaplama malzemesi'],
  ['изогнутая', 'kavisli'],
  ['зеленая', 'yeşil'],
  ['твердый', 'katı'],
  ['твердые', 'katı'],
  ['освежитель', 'ferahlatıcı'],
  ['бегония', 'begonya'],
  ['жасминовая', 'yasemin'],
  ['жемчужина', 'inci'],
  ['ароматная', 'aromatik'],
  ['шарики', 'küreler'],
  ['углеводов', 'karbonhidrat'],
  ['элемент молодости', 'gençlik elementi'],
  ['мультиминеральные', 'multi mineral'],
  ['молодости', 'gençlik'],
  ['элемент', 'element'],
  ['спирулина', 'spirulina'],
  ['протеин', 'protein'],
  ['желатиновые', 'jelatin'],
  ['коферментом', 'koenzim'],
  ['сандалии', 'sandalet'],
  ['эластичные', 'esnek'],
  ['водяной куб', 'su küpü'],
  ['платиновый хлопок', 'platin pamuk'],
  ['элегантная цветочная мелодия', 'zarif çiçek melodisi'],
  ['звезда', 'yıldız'],
  ['женские духи', 'kadın parfümü'],
  ['ежедневный уход', 'günlük bakım'],
  ['интимной', 'özel'],
  ['гигиены', 'hijyen'],
  ['очищающее средство', 'temizleyici'],
  ['белой обувью', 'beyaz ayakkabı'],
  ['две бутылки', 'iki şişe'],
  ['в упаковке', 'pakette'],
  ['пакете', 'pakette'],
  ['предмета', 'parça'],
  ['предметов', 'parça'],
  ['серия', 'seri'],
  ['серии', 'seri'],
  ['медицинского класса', 'medikal sınıf'],
  ['влажная туалетная салфетка', 'nemli tuvalet mendili'],
  ['удобно брать с собой', 'yanınıza almak için pratik'],
  ['дороге и в поездках', 'yolculuklar için'],
  ['экспериментальный', 'deneysel'],
  ['инструментов', 'alet'],
  ['гладкости', 'pürüzsüzlük'],
  ['придания', 'verme'],
  ['тестируем', 'test'],
  ['скраб-пенка', 'scrub köpük'],
  ['3-в-1', '3\'ü 1 arada'],
  ['3 в 1', '3\'ü 1 arada'],
  ['жирности', 'yağlılık'],
  ['г', 'g'],
  ['мл', 'ml'],
  ['кг', 'kg'],
  ['мм', 'mm'],
  ['см', 'cm'],
];

export function isBadTranslation(text) {
  if (!text) return false;
  return /MYMEMORY\s+WARNING/i.test(text) || /TRANSLATED\.NET\/DOC\/USAGELIMITS/i.test(text);
}

export function glossaryTranslate(text) {
  if (!text?.trim()) return '';
  let result = text.trim();

  const sorted = [...PHRASES].sort((a, b) => b[0].length - a[0].length);
  for (const [ru, tr] of sorted) {
    const re = new RegExp(ru.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
    result = result.replace(re, tr);
  }

  // Kiril kalan uzun kelimeleri olduğu gibi bırak; kısa Rusça parçaları temizle
  result = result
    .replace(/\s+/g, ' ')
    .replace(/\s*,\s*/g, ', ')
    .trim();

  return result;
}

export function splitFeatureBullets(text) {
  return text
    .split(/(?=[А-ЯA-ZÇĞİÖŞÜ][а-яa-zçğıöşü])/)
    .map((s) => s.trim())
    .filter((s) => s.length > 8 && !isBadTranslation(s));
}
